### ISSUE TITLE
Discord CDN links no longer work

### ISSUE THREAD

**Issue by GMPranav** [Swyter/poptools#1]
Since discord made their CDN links expire, the windowed mode profile files [linked in the readme](https://github.com/Swyter/poptools/blob/main/README.md#natively-launch-the-games-in-windowed-mode) no longer work.

The possible options to fix this are:
- Change them to message links instead of cdn links. Requires the user to have a discord account and be in the speedrunning server.
- Host them in another platform (possibly GitHub itself) and then link that instead.

**Comment by Swyter** [comment]
I usually just save the temporary Discord links in the Wayback Machine and link those. 

Just updated the Readme in https://github.com/Swyter/poptools/commit/c1535e8df1e0e0a4336ba813ec041d0bc86f0ed8, thanks for noticing. Already did this for a bunch of my projects, but this one slipped between the cracks.
